function v = ComputeVariance(s, mu)
  % ComputeAccuracy computes the proportion of correct guessed classes
  % of total classes tried. It sums the list of instances where y - facit
  % is equal to our guessed class, extracted as the max prob-value from our
  % distribution vector P, generated by evaluating the current parameters W and b.
  %
  % INPUT:
  %   s -- The current data batch of size (d, N_batch)
  %
  % OUTPUT:
  %   mu -- The scalar accuracy as calculated by the fraction of correct/total.
  % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
  n = size(s, 2);
  v = var(s, 0, 2);
  v = v*(n-1)/n;
endfunction
