function acc = ComputeAccuracy(X, y, W, b, N)
  % ComputeAccuracy computes the proportion of correct guessed classes
  % of total classes tried. It sums the list of instances where y - facit
  % is equal to our guessed class, extracted as the max prob-value from our
  % distribution vector P, generated by evaluating the current parameters W and b.
  %
  % INPUT:
  %   X -- The current data batch of size (d, N_batch)
  %   y -- The current label vector of size (1, N_batch)
  %   W -- The current weight cell of size (2,1) containing W1 and W2
  %   b -- The current bias cell of size (2, 1) containing b1 and b2
  %   N -- The current batch size, i.e. N == N_batch
  %
  % OUTPUT:
  %   acc -- The scalar accuracy as calculated by the fraction of correct/total.
  % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
  layers = length(W);
  cache = EvaluateClassifier(X, W, b);
  [_,PMaxIdx] = max(cache{2*layers,1});
  acc = sum(y' == PMaxIdx)/N;
endfunction
